services:
  book-tracker:
    build: .
    container_name: book_tracker_app
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: "change-this-to-a-long-random-secret"
      ADMIN_USER: "veli"
      ADMIN_PASS: "veli123"
    volumes:
      - ./data:/app/data
    restart: always
